name: Hive Pool Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes
    - cron: '0 0 * * *'    # Update graph daily at midnight
  workflow_dispatch:
  
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install requests

    - name: Install dependencies
      run: pip install requests pandas plotly
    
    - name: Run monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python monitor.py
       - name: Generate graph (runs daily)
      if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
      run: python generate_graph.py
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/index.html
        git commit -m "Update live graph"
        git push
