name: Hive Pool Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # Checks every 5 mins
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install requests pandas plotly
      - run: python monitor.py
      - run: python generate_graph.py
